### ISSUE TITLE
Getting ecliptic data for getAllPlanets but i want  Equatorial Coordinate data.

### ISSUE THREAD

**Issue by bipinrajbhar** [rish-0-0/astroreha#1]
Can you help with this?

I know you are getting all planets data from ephemeris package but I don't know how to convert that.

**Comment by rish-0-0** [comment]
Does the getUTCPosition function not serve purpose? I would love to accept a proper functionality for this exact issue though.

**Comment by bipinrajbhar** [comment]
Actually I build an app using astrologyapi but now I am trying to build a node API myself.

**Comment by pavan336477** [comment]
Hi Rishabh, we actually got stuck in middle, at planets position raw data. Please help us to convert that Raw data to get regular planetary degrees which we'll find in every Astrology App.

**Comment by rish-0-0** [comment]
[getAllPlanets.txt](https://github.com/rish-0-0/astroreha/files/5119764/planetCheck.txt)

This textfile above is generated by running the getAllPlanets function

This is all as per the usage of [ephemeris](https://www.npmjs.com/package/ephemeris)

@bipinrajbhar It does contain equatorial units: If by that you're referring to RA and DEC
@pavan336477 The output also contains the required format for you to use i.e, "degrees" "minutes" and "seconds"

Please do let me know if I misunderstood your question.
